---
platform: linux

image_resource: 
  type: docker-image
  source:
    repository: maven
    tag: latest
    
inputs:
  - name: concourse-java-maven-test-prj1
  
outputs:
  - name: resource-app
  
run:
  path: concourse-java-maven-test-prj1/ci/build.sh
